import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
import fontkit from "@pdf-lib/fontkit";
import { PDFArray, PDFDict, PDFDocument, PDFName } from "pdf-lib";
import { blankPage, emptyDocument, newObject } from "../../src/state/model";
import { saveProject, openProject } from "../../src/state/project";
import { inspectDirectText } from "../../src/direct/content";
async function fixture(downstream = false) {
  const pdf = await PDFDocument.create(); pdf.registerFontkit(fontkit);
  const p = pdf.addPage([420, 595]);
  const font = await pdf.embedFont(await readFile("public/assets/NotoSansJP-Regular.otf"), { subset: false });
  const following = font.encodeText("後続").toString();
  const first = font.encodeText("日本語の縦書き").toString(), second = font.encodeText("隣の列").toString();
  await pdf.flush();
  const dict = pdf.context.lookup(font.ref, PDFDict); dict.set(PDFName.of("Encoding"), PDFName.of("Identity-V"));
  dict.lookup(PDFName.of("DescendantFonts"), PDFArray).lookup(0, PDFDict).set(PDFName.of("DW2"), pdf.context.obj([880, -1000]));
  p.node.set(PDFName.of("Resources"), pdf.context.obj({ Font: { F1: font.ref } }));
  p.node.set(PDFName.of("Contents"), pdf.context.register(pdf.context.flateStream(`BT /F1 20 Tf ${downstream ? "80 Tz 2 Tc 3 Ts" : ""} 1 0 0 1 300 520 Tm ${downstream ? `[${first} 125] TJ /F1 14 Tf ${following} Tj /F1 20 Tf` : `${first} Tj`} 1 0 0 1 260 520 Tm ${second} Tj ET`)));
  return Buffer.from(await pdf.save());
}
test("vertical source editing preserves neighbour, previews alternate glyphs, and saves an editable Identity-V PDF", async ({ page }, info) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  const chooser = page.waitForEvent("filechooser"); await page.getByRole("button", { name: "PDFを開く", exact: true }).click();
  await (await chooser).setFiles({ name: "vertical.pdf", mimeType: "application/pdf", buffer: await fixture() });
  await expect(page.locator(".viewer-scroll .page-view[data-rendered=true]")).toBeVisible();
  const original = page.locator(".viewer-scroll .textLayer span").filter({ hasText: /^日本語の縦書き$/ });
  const neighbour = page.locator(".viewer-scroll .textLayer span").filter({ hasText: /^隣の列$/ });
  await expect(original).toBeVisible(); const before = await neighbour.boundingBox();
  await page.getByRole("button", { name: "ツール", exact: true }).click();
  await page.getByRole("button", { name: "既存文字", exact: true }).click(); await original.dblclick();
  await expect(page.getByLabel("文字の方向")).toHaveValue("vertical");
  await page.getByLabel("テキスト内容").fill("変更、。「」ー");
  const overlay = page.locator(".viewer-scroll .editable-text[data-layout-ready=true]");
  await expect(overlay).toHaveText("変更、。「」ー"); await expect(overlay.locator("use")).toHaveCount(7);
  await expect(original).toHaveCount(0); const after = await neighbour.boundingBox();
  expect(after!.x).toBeCloseTo(before!.x, 1); expect(after!.y).toBeCloseTo(before!.y, 1);
  await page.getByRole("button", { name: /^元に戻す/ }).click(); await page.getByRole("button", { name: /^元に戻す/ }).click();
  await expect(original).toHaveCount(1); await page.getByRole("button", { name: /^やり直す/ }).click(); await page.getByRole("button", { name: /^やり直す/ }).click();
  await expect(overlay).toHaveText("変更、。「」ー");
  const download = page.waitForEvent("download"); await page.getByRole("button", { name: "保存", exact: true }).click();
  const path = info.outputPath("vertical-saved.pdf"); await (await download).saveAs(path);
  const saved = await readFile(path); const runs = (await inspectDirectText(new Uint8Array(saved), 0)).runs;
  expect(runs.map(r => r.text)).toContain("変更、。「」ー"); expect(runs.map(r => r.text)).not.toContain("日本語の縦書き");
  await page.reload();
  const reopen = page.waitForEvent("filechooser"); await page.getByRole("button", { name: "PDFを開く", exact: true }).click();
  await (await reopen).setFiles({ name: "vertical-saved.pdf", mimeType: "application/pdf", buffer: saved });
  const replacement = page.locator(".viewer-scroll .textLayer span").filter({ hasText: /^変更、。「」ー$/ });
  await expect(replacement).toBeVisible();
  await expect(page.locator(".viewer-scroll .page-view[data-rendered=true]")).toBeVisible();
  const pixels = await page.locator(".viewer-scroll canvas").first().evaluate((canvas: HTMLCanvasElement) => {
    const ctx = canvas.getContext("2d")!, sx = canvas.width / 420, sy = canvas.height / 595;
    return Array.from({ length: 7 }, (_, row) => {
      const data = ctx.getImageData(Math.floor(290 * sx), Math.floor((75 + row * 20) * sy), Math.ceil(20 * sx), Math.ceil(20 * sy)).data;
      let ink = 0; for (let i = 0; i < data.length; i += 4) if (data[i] < 128 && data[i + 1] < 128 && data[i + 2] < 128) ink++;
      return ink;
    });
  });
  expect(pixels.every(n => n > 0)).toBe(true);
  await page.getByRole("button", { name: "ツール", exact: true }).click(); await page.getByRole("button", { name: "既存文字", exact: true }).click();
  await replacement.dblclick(); await expect(page.getByLabel("テキスト内容")).toHaveValue("変更、。「」ー");
  expect(errors).toEqual([]);
});

test("vertical removal keeps PDF.js downstream placement with character spacing, scaling, rise and TJ", async ({ page }) => {
  await page.goto("/"); const chooser = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "PDFを開く", exact: true }).click();
  await (await chooser).setFiles({ name: "vertical-advance.pdf", mimeType: "application/pdf", buffer: await fixture(true) });
  const following = page.locator(".viewer-scroll .textLayer span").filter({ hasText: /^後続$/ });
  await expect(following).toBeVisible(); const before = await following.boundingBox();
  await page.getByRole("button", { name: "ツール", exact: true }).click(); await page.getByRole("button", { name: "既存文字", exact: true }).click();
  await page.locator(".viewer-scroll .textLayer span").filter({ hasText: /^日本語の縦書き$/ }).dblclick();
  await expect(page.getByLabel("文字の方向")).toHaveValue("vertical");
  await expect(page.locator(".viewer-scroll .textLayer span").filter({ hasText: /^日本語の縦書き$/ })).toHaveCount(0);
  await expect(page.locator(".viewer-scroll .page-view[data-rendered=true]")).toBeVisible();
  const after = await following.boundingBox(); expect(after!.x).toBeCloseTo(before!.x, 2); expect(after!.y).toBeCloseTo(before!.y, 2);
});

test("switches registered text between directions, wraps vertically by height and restores the project", async ({ page }, info) => {
  const d = emptyDocument("vertical-layout.pdf"); d.pages = [blankPage()];
  d.pages[0].objects = [{ ...newObject("text", 200, 40), text: "ABCDEF", fontSize: 20, width: 180, height: 40 }];
  await page.goto("/"); let chooser = page.waitForEvent("filechooser");
  await page.getByRole("button", { name: "PDFを開く", exact: true }).click();
  await (await chooser).setFiles({ name: "vertical-layout.kpdf", mimeType: "application/zip", buffer: Buffer.from(await saveProject(d)) });
  const overlay = page.locator(".viewer-scroll .editable-text[data-layout-ready=true]"); await expect(overlay).toBeVisible();
  await page.locator(".viewer-scroll .object-layer > g").first().click();
  chooser = page.waitForEvent("filechooser"); await page.getByRole("button", { name: "フォントを追加", exact: true }).click();
  await (await chooser).setFiles("public/assets/pdfjs/standard_fonts/LiberationSans-Regular.ttf");
  await expect(overlay).toHaveAttribute("font-family", /^Kikki/);
  const fontId = await page.getByLabel("フォント", { exact: true }).inputValue();
  await page.getByLabel("文字の方向").selectOption("vertical"); await expect(overlay.locator("use")).toHaveCount(6);
  await expect(page.getByLabel("フォント", { exact: true })).toHaveValue(fontId);
  await expect(page.getByRole("button", { name: "太字", exact: true })).toBeDisabled();
  await page.getByLabel("height", { exact: true }).fill("40"); await page.getByLabel("高さに合わせて折り返す", { exact: true }).check();
  await expect(page.locator(".text-layout-summary")).toContainText("3 列");
  await page.getByRole("button", { name: "文字に合わせて幅を調整", exact: true }).click();
  await expect(page.getByLabel("width", { exact: true })).toHaveValue("70");
  await expect(page.getByLabel("x", { exact: true })).toHaveValue("150");
  await page.getByLabel("文字の方向").selectOption("horizontal"); await expect(overlay.locator("tspan")).toHaveCount(1);
  await page.getByLabel("文字の方向").selectOption("vertical"); await expect(overlay.locator("use")).toHaveCount(6);
  let download = page.waitForEvent("download"); await page.locator("summary").filter({ hasText: "ファイル" }).click();
  await page.getByRole("button", { name: "編集プロジェクトを保存", exact: true }).click();
  const project = info.outputPath("vertical-layout.kpdf"); await (await download).saveAs(project);
  const restored = await openProject(new Uint8Array(await readFile(project)));
  expect(restored.pages[0].objects[0].writingMode).toBe("vertical"); expect(restored.pages[0].objects[0].fontId).toBe(fontId);
  download = page.waitForEvent("download"); await page.getByRole("button", { name: "保存", exact: true }).click();
  const pdf = info.outputPath("vertical-custom.pdf"); await (await download).saveAs(pdf);
  expect((await inspectDirectText(new Uint8Array(await readFile(pdf)), 0)).runs.map(r => r.text)).toEqual(["ABCDEF"]);
});
